"""Laundering Heuristics Module for Cryptographic Transaction Topology Analysis.

Analyzes transaction graphs generated by BlockchainGraphTracer to detect:
  1. Peeling Chain Patterns: Asymmetric splits (> 80/20) occurring within a short
     time delta (< 1 hour) where an address peels off a fraction and forwards the
     majority to an intermediary.
  2. Rapid Sweep Events: Exchange deposit proxy consolidation where > 95% of incoming
     funds are forwarded to a primary VASP hot wallet within a narrow time window.
  3. Graph Risk Annotation: Enriches NetworkX nodes and edges with investigative flags.
"""

from copy import deepcopy
import sys
from typing import Any, Dict, List, Optional

import networkx as nx

from data_ingestor import IngestionEngine
from graph_engine import BlockchainGraphTracer


class LaunderingHeuristics:
    """Detection heuristics for money laundering topologies on public ledgers."""

    @staticmethod
    def detect_peeling_chain(tx_list: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Detects the classic cryptocurrency peeling chain pattern.

        A peeling chain is characterized by an address transferring the majority of
        funds to an intermediary/layering address while 'peeling' a smaller fraction
        off (gas fees, mule fee, or micro cash-out).

        Flag condition: Consecutive transactions within a short time delta (< 1 hour /
        3600 seconds) having an asymmetric split ratio (> 80/20, i.e., > 0.80 and < 0.20).

        Args:
            tx_list: List of transaction dictionaries (typically outbound transfers
                     from a single wallet address).

        Returns:
            Dictionary with detection verdict, participating transactions, split
            ratios, time delta, and descriptive intelligence text.
        """
        if not tx_list or len(tx_list) < 2:
            return {
                "is_peeling_chain": False,
                "description": "Insufficient transactions (minimum 2 required) to detect a peeling chain.",
            }

        # Sort transactions chronologically
        sorted_txs = sorted(tx_list, key=lambda tx: int(tx.get("timestamp", 0)))

        # Evaluate consecutive transaction pairs
        for i in range(len(sorted_txs) - 1):
            tx_a = sorted_txs[i]
            tx_b = sorted_txs[i + 1]

            amt_a = float(tx_a.get("amount_crypto", 0.0))
            amt_b = float(tx_b.get("amount_crypto", 0.0))
            total_split = amt_a + amt_b

            if total_split <= 0:
                continue

            ts_a = int(tx_a.get("timestamp", 0))
            ts_b = int(tx_b.get("timestamp", 0))
            time_delta = abs(ts_b - ts_a)

            ratio_a = amt_a / total_split
            ratio_b = amt_b / total_split

            max_ratio = max(ratio_a, ratio_b)
            min_ratio = min(ratio_a, ratio_b)

            # Check rule: consecutive transactions within < 1 hr with > 80/20 ratio
            if time_delta < 3600 and max_ratio > 0.80 and min_ratio < 0.20:
                primary_tx = tx_a if amt_a >= amt_b else tx_b
                peeled_tx = tx_b if amt_a >= amt_b else tx_a

                return {
                    "is_peeling_chain": True,
                    "primary_tx": primary_tx,
                    "peeled_tx": peeled_tx,
                    "primary_amount": round(max(amt_a, amt_b), 4),
                    "peeled_amount": round(min(amt_a, amt_b), 4),
                    "primary_ratio": round(max_ratio, 4),
                    "peeled_ratio": round(min_ratio, 4),
                    "time_delta_seconds": time_delta,
                    "primary_tx_hash": primary_tx.get("tx_hash"),
                    "peeled_tx_hash": peeled_tx.get("tx_hash"),
                    "primary_destination": primary_tx.get("to_address"),
                    "peeled_destination": peeled_tx.get("to_address"),
                    "description": (
                        f"Peeling chain confirmed: {max_ratio * 100:.1f}% forwarded to "
                        f"{primary_tx.get('to_address')} ({max(amt_a, amt_b):.2f} ETH) and "
                        f"{min_ratio * 100:.1f}% peeled to {peeled_tx.get('to_address')} "
                        f"({min(amt_a, amt_b):.2f} ETH) within {time_delta}s."
                    ),
                }

        return {
            "is_peeling_chain": False,
            "description": "No asymmetric split (> 80/20 within < 1 hr) detected in consecutive transactions.",
        }

    @staticmethod
    def detect_rapid_sweep(
        graph: nx.DiGraph,
        deposit_node: str,
        hot_wallet_node: str,
    ) -> bool:
        """Detects rapid sweep behavior from a deposit proxy to a VASP hot wallet.

        Flags when an intermediate address received funds and forwarded > 95% of
        them to a known VASP hot wallet within a narrow time window (< 2 hours = 7200 seconds),
        characteristic of automated exchange deposit consolidation routines.

        Args:
            graph: Directed NetworkX transaction graph.
            deposit_node: Source deposit proxy wallet address.
            hot_wallet_node: Destination VASP hot wallet address.

        Returns:
            True if consolidation ratio > 95% within the narrow time window, False otherwise.
        """
        if not graph.has_edge(deposit_node, hot_wallet_node):
            return False

        # Calculate total incoming funds and latest inflow timestamp
        in_edges = list(graph.in_edges(deposit_node, data=True))
        if not in_edges:
            return False

        total_inflow = sum(float(data.get("amount_crypto", 0.0)) for _, _, data in in_edges)
        if total_inflow <= 0:
            return False

        latest_inflow_ts = max(int(data.get("timestamp", 0)) for _, _, data in in_edges)

        # Retrieve outbound transfer to hot wallet
        edge_data = graph[deposit_node][hot_wallet_node]
        sweep_outflow = float(edge_data.get("amount_crypto", 0.0))
        sweep_ts = int(edge_data.get("timestamp", 0))

        # Check ratio and time delta
        forward_ratio = sweep_outflow / total_inflow
        time_delta = sweep_ts - latest_inflow_ts

        # Forwarded > 95% within narrow time window (0 to 7200 seconds)
        if forward_ratio >= 0.95 and 0 <= time_delta <= 7200:
            return True

        return False

    @classmethod
    def annotate_graph_risks(cls, graph: nx.DiGraph) -> nx.DiGraph:
        """Annotates graph nodes and edges with laundering risk flags.

        Evaluates peeling chain and rapid sweep heuristics across the graph and sets:
          - node['is_peeling_chain'] = True
          - edge['is_peeling_chain'] = True
          - node['is_rapid_sweep'] = True
          - edge['is_rapid_sweep'] = True

        Args:
            graph: NetworkX DiGraph produced by BlockchainGraphTracer.

        Returns:
            Enriched NetworkX DiGraph.
        """
        annotated = graph  # in-place modification and return

        for node in list(annotated.nodes):
            out_edges = list(annotated.out_edges(node, data=True))

            # 1. Peeling Chain Evaluation
            if len(out_edges) >= 2:
                tx_list = [data for _, _, data in out_edges]
                peeling_result = cls.detect_peeling_chain(tx_list)
                if peeling_result.get("is_peeling_chain"):
                    annotated.nodes[node]["is_peeling_chain"] = True
                    annotated.nodes[node]["peeling_chain_data"] = peeling_result

                    p_hash = peeling_result.get("primary_tx_hash")
                    f_hash = peeling_result.get("peeled_tx_hash")

                    for u, v, data in out_edges:
                        if data.get("tx_hash") in (p_hash, f_hash):
                            annotated[u][v]["is_peeling_chain"] = True
                            annotated[u][v]["peeling_role"] = (
                                "primary_forward" if data.get("tx_hash") == p_hash else "peeled_fraction"
                            )

            # 2. Rapid Sweep Evaluation
            for _, dest_node, data in out_edges:
                dest_nodetype = annotated.nodes[dest_node].get("nodetype", "")
                src_nodetype = annotated.nodes[node].get("nodetype", "")

                if dest_nodetype == "vasp_hot" or src_nodetype == "vasp_deposit":
                    if cls.detect_rapid_sweep(annotated, node, dest_node):
                        annotated.nodes[node]["is_rapid_sweep"] = True
                        annotated.nodes[dest_node]["is_rapid_sweep_target"] = True
                        annotated[node][dest_node]["is_rapid_sweep"] = True

        return annotated


# ---------------------------------------------------------------------------
# Standalone Execution / Heuristics Verification Check
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    if hasattr(sys.stdout, "reconfigure"):
        try:
            sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        except Exception:
            pass

    print("=" * 80)
    print(" CRYPTOCURRENCY LAUNDERING HEURISTICS & TOPOLOGY ANALYSIS REPORT")
    print("=" * 80)

    # Step 1: Initialize Ingestion and Tracing Pipeline
    ingestor = IngestionEngine(mode="mock")
    tracer = BlockchainGraphTracer(ingestor)

    target_address = "0x_suspect_theft_initiator"
    print(f"\n[1] Running BFS Graph Trace on Target Address: '{target_address}'")
    tracer.trace_path(target_address, max_hops=5, min_amount_threshold=0.01)

    # Step 2: Run Heuristic Risk Annotations
    heuristics = LaunderingHeuristics()
    annotated_graph = heuristics.annotate_graph_risks(tracer.graph)

    # Metric 1: Total nodes and edges traversed
    total_nodes = annotated_graph.number_of_nodes()
    total_edges = annotated_graph.number_of_edges()
    print(f"\n[2] Graph Topology Metrics:")
    print(f"    * Total Nodes Traversed : {total_nodes}")
    print(f"    * Total Edges Traversed : {total_edges}")

    # Metric 2: Shortest path to the nearest VASP
    vasps = tracer.find_nearest_vasps(target_address)
    print(f"\n[3] Shortest Path to Nearest VASP:")
    if vasps:
        nearest_vasp = vasps[0]
        print(f"    * Target Exchange : {nearest_vasp['label']}")
        print(f"    * Hop Distance    : {nearest_vasp['hop_distance']}")
        print(f"    * Traversal Path  : {nearest_vasp['path_str']}")
        print(f"    * Total Volume    : {nearest_vasp['total_volume_crypto']} ETH")
        print(f"    * Compliance Email: {nearest_vasp['compliance_email']}")
    else:
        print("    * No reachable VASP identified.")

    # Metric 3: Halting condition verification (Mixer check)
    print(f"\n[4] Sanctioned Mixer Terminal Halting Check:")
    mixer_targets = [
        target for target in tracer.terminal_targets if target.get("nodetype") == "mixer"
    ]
    for m in mixer_targets:
        out_degree = annotated_graph.out_degree(m["address"])
        print(f"    * Mixer Identified : {m['label']} ({m['address']})")
        print(f"    * Terminal Status  : Halting Enforced (Out-degree = {out_degree}, No infinite loops)")

    # Metric 4: Identified Peeling Chains
    print(f"\n[5] Identified Peeling Chains:")
    peeling_count = 0
    for node, data in annotated_graph.nodes(data=True):
        if data.get("is_peeling_chain"):
            peeling_count += 1
            info = data.get("peeling_chain_data", {})
            print(f"    * Node [{node}]:")
            print(f"      - {info.get('description')}")
            print(f"      - Split: {info.get('primary_amount')} ETH ({info.get('primary_ratio')*100:.1f}%) -> {info.get('primary_destination')}")
            print(f"      - Peeled: {info.get('peeled_amount')} ETH ({info.get('peeled_ratio')*100:.1f}%) -> {info.get('peeled_destination')}")
            print(f"      - Time Delta: {info.get('time_delta_seconds')}s")

    if peeling_count == 0:
        print("    * No peeling chains detected.")

    # Metric 5: Identified Rapid Sweep Events
    print(f"\n[6] Identified Rapid Sweep Events:")
    sweep_count = 0
    for u, v, data in annotated_graph.edges(data=True):
        if data.get("is_rapid_sweep"):
            sweep_count += 1
            in_edges = annotated_graph.in_edges(u, data=True)
            inflow = sum(float(d.get("amount_crypto", 0.0)) for _, _, d in in_edges)
            outflow = float(data.get("amount_crypto", 0.0))
            ratio = (outflow / inflow) * 100 if inflow else 0
            print(f"    * Sweep [{u} -> {v}]:")
            print(f"      - Inflow: {inflow:.2f} ETH | Swept Outflow: {outflow:.2f} ETH ({ratio:.2f}%)")
            print(f"      - TX Hash: {data.get('tx_hash')}")

    if sweep_count == 0:
        print("    * No rapid sweeps detected.")

    # Verification Check
    print("\n" + "=" * 80)
    print(" VERIFICATION CHECK RESULTS:")
    print("=" * 80)
    expected_path = (
        "0x_suspect_theft_initiator -> 0x_mule_account_alpha -> "
        "0x_peeling_layer_01 -> 0x_dep_coindcx_user_4492 -> CoinDCX Main Inflow Vault"
    )
    actual_path = nearest_vasp["path_str"] if vasps else ""
    path_ok = actual_path == expected_path
    hop_ok = nearest_vasp["hop_distance"] == 4 if vasps else False
    mixer_halt_ok = len(mixer_targets) > 0 and all(
        annotated_graph.out_degree(m["address"]) == 0 for m in mixer_targets
    )

    print(f" [PASS] Systematic Path Traversal Match : {path_ok}")
    print(f"        Actual Path: {actual_path}")
    print(f" [PASS] Halting at Tornado Cash Mixer   : {mixer_halt_ok}")
    print(f" [PASS] Nearest VASP Hop Count == 4     : {hop_ok} (Hop count: {nearest_vasp['hop_distance'] if vasps else 'N/A'})")
    print(f" [PASS] Peeling Chains Identified       : {peeling_count >= 2} (Found: {peeling_count})")
    print(f" [PASS] Rapid Sweep Detected            : {sweep_count >= 1} (Found: {sweep_count})")
    print("=" * 80)
