export const MOCK_TRACE_FALLBACK: Record<string, any> = {
  '0x_suspect_theft_initiator': {
    status: 'success',
    root_address: '0x_suspect_theft_initiator',
    chain: 'ETH',
    elements: [
      {
        data: {
          id: '0x_suspect_theft_initiator',
          label: 'Suspect Theft Initiator',
          entity_type: 'Suspect Wallet',
          nodetype: 'suspect',
          risk_tier: 'Critical',
          hop_distance: 0,
          balance: 0.0,
          in_primary_path: true,
          is_root: true,
          fiu_registered: false,
          compliance_email: null,
        },
      },
      {
        data: {
          id: '0x_mule_account_alpha',
          label: 'Mule Account Alpha',
          entity_type: 'Layering Mule',
          nodetype: 'unattributed',
          risk_tier: 'High',
          hop_distance: 1,
          balance: 0.0,
          in_primary_path: true,
          is_root: false,
          fiu_registered: false,
          compliance_email: null,
        },
      },
      {
        data: {
          id: '0x_tornado_cash_vault',
          label: 'Tornado Cash 100 ETH Vault (OFAC Sanctioned)',
          entity_type: 'Mixer',
          nodetype: 'mixer',
          risk_tier: 'Critical',
          hop_distance: 1,
          balance: 25.0,
          in_primary_path: false,
          is_terminal: true,
          is_root: false,
          fiu_registered: false,
          compliance_email: 'none/sanctioned',
        },
      },
      {
        data: {
          id: '0x_peeling_layer_01',
          label: 'Peeling Layer 01',
          entity_type: 'Layering Mule',
          nodetype: 'unattributed',
          risk_tier: 'High',
          hop_distance: 2,
          balance: 0.0,
          in_primary_path: true,
          is_root: false,
          fiu_registered: false,
          compliance_email: null,
        },
      },
      {
        data: {
          id: '0x_peeled_fee_sink_alpha',
          label: 'Peeled Fee Sink',
          entity_type: 'Fee Sink',
          nodetype: 'unattributed',
          risk_tier: 'Medium',
          hop_distance: 2,
          balance: 10.0,
          in_primary_path: false,
          is_root: false,
          fiu_registered: false,
          compliance_email: null,
        },
      },
      {
        data: {
          id: '0x_mule_loop_cycler',
          label: 'Cyclic Mule Account',
          entity_type: 'Cyclic Layer',
          nodetype: 'unattributed',
          risk_tier: 'Medium',
          hop_distance: 2,
          balance: 0.05,
          in_primary_path: false,
          is_root: false,
          fiu_registered: false,
          compliance_email: null,
        },
      },
      {
        data: {
          id: '0x_dep_coindcx_user_4492',
          label: 'CoinDCX Dynamic Deposit Proxy (user_4492)',
          entity_type: 'Centralized Exchange Deposit Proxy',
          nodetype: 'vasp_deposit',
          risk_tier: 'Low',
          hop_distance: 3,
          balance: 0.2,
          in_primary_path: true,
          is_root: false,
          fiu_registered: true,
          compliance_email: 'compliance@coindcx.com',
        },
      },
      {
        data: {
          id: '0x_peeled_gas_sink_layer01',
          label: 'Gas Relayer Sink',
          entity_type: 'Fee Sink',
          nodetype: 'unattributed',
          risk_tier: 'Low',
          hop_distance: 3,
          balance: 5.0,
          in_primary_path: false,
          is_root: false,
          fiu_registered: false,
          compliance_email: null,
        },
      },
      {
        data: {
          id: 'CoinDCX Main Inflow Vault',
          label: 'CoinDCX Main Inflow Vault',
          entity_type: 'Centralized Exchange Hot Vault',
          nodetype: 'vasp_hot',
          risk_tier: 'Low',
          hop_distance: 4,
          balance: 79.8,
          in_primary_path: true,
          is_terminal: true,
          is_root: false,
          fiu_registered: true,
          compliance_email: 'compliance@coindcx.com',
        },
      },
      // Directed Edges
      {
        data: {
          id: '0x_suspect_theft_initiator->0x_mule_account_alpha',
          source: '0x_suspect_theft_initiator',
          target: '0x_mule_account_alpha',
          amount: 95.0,
          tx_hash: '0xtx_theft_to_mule_alpha_01',
          timestamp: 1711929600,
          is_peeling: false,
          is_sweep: false,
          in_primary_path: true,
        },
      },
      {
        data: {
          id: '0x_suspect_theft_initiator->0x_tornado_cash_vault',
          source: '0x_suspect_theft_initiator',
          target: '0x_tornado_cash_vault',
          amount: 25.0,
          tx_hash: '0xtx_theft_to_tornado_obfuscation',
          timestamp: 1711929700,
          is_peeling: false,
          is_sweep: false,
          in_primary_path: false,
        },
      },
      {
        data: {
          id: '0x_mule_account_alpha->0x_peeling_layer_01',
          source: '0x_mule_account_alpha',
          target: '0x_peeling_layer_01',
          amount: 85.0,
          tx_hash: '0xtx_mule_alpha_to_peeling_layer',
          timestamp: 1711930800,
          is_peeling: true,
          is_sweep: false,
          in_primary_path: true,
        },
      },
      {
        data: {
          id: '0x_mule_account_alpha->0x_peeled_fee_sink_alpha',
          source: '0x_mule_account_alpha',
          target: '0x_peeled_fee_sink_alpha',
          amount: 10.0,
          tx_hash: '0xtx_mule_alpha_peeled_cut',
          timestamp: 1711931000,
          is_peeling: true,
          is_sweep: false,
          in_primary_path: false,
        },
      },
      {
        data: {
          id: '0x_mule_account_alpha->0x_mule_loop_cycler',
          source: '0x_mule_account_alpha',
          target: '0x_mule_loop_cycler',
          amount: 1.0,
          tx_hash: '0xtx_mule_alpha_to_cycler',
          timestamp: 1711931100,
          is_peeling: false,
          is_sweep: false,
          in_primary_path: false,
        },
      },
      {
        data: {
          id: '0x_peeling_layer_01->0x_dep_coindcx_user_4492',
          source: '0x_peeling_layer_01',
          target: '0x_dep_coindcx_user_4492',
          amount: 80.0,
          tx_hash: '0xtx_peeling_to_coindcx_dep',
          timestamp: 1711936800,
          is_peeling: false,
          is_sweep: false,
          in_primary_path: true,
        },
      },
      {
        data: {
          id: '0x_peeling_layer_01->0x_peeled_gas_sink_layer01',
          source: '0x_peeling_layer_01',
          target: '0x_peeled_gas_sink_layer01',
          amount: 5.0,
          tx_hash: '0xtx_peeling_gas_sink',
          timestamp: 1711937000,
          is_peeling: true,
          is_sweep: false,
          in_primary_path: false,
        },
      },
      {
        data: {
          id: '0x_mule_loop_cycler->0x_mule_account_alpha',
          source: '0x_mule_loop_cycler',
          target: '0x_mule_account_alpha',
          amount: 0.95,
          tx_hash: '0xtx_cycler_back_to_mule_alpha',
          timestamp: 1711931200,
          is_peeling: false,
          is_sweep: false,
          in_primary_path: false,
        },
      },
      {
        data: {
          id: '0x_dep_coindcx_user_4492->CoinDCX Main Inflow Vault',
          source: '0x_dep_coindcx_user_4492',
          target: 'CoinDCX Main Inflow Vault',
          amount: 79.8,
          tx_hash: '0xtx_coindcx_internal_sweep_hot',
          timestamp: 1711940400,
          is_peeling: false,
          is_sweep: true,
          in_primary_path: true,
        },
      },
    ],
    attribution_summary: {
      confidence_score_pct: 85.89,
      confidence_band: 'High',
      breakdown: {
        hop_distance_decay: 0.6141,
        value_preservation: 0.84,
        velocity_continuity: 1.0,
        base_score: 0.8089,
        direct_sweep_bonus: 0.1,
        mixer_proximity_penalty: 0.05,
        hop_count: 4,
        amount_sent: 95.0,
        amount_received: 79.8,
      },
      target_vasp_summary: {
        name: 'CoinDCX Main Inflow Vault',
        entity_type: 'Centralized Exchange',
        jurisdiction: 'India',
        nodetype: 'vasp_hot',
        fiu_registered: true,
        compliance_email: 'compliance@coindcx.com',
      },
      trail_path: [
        '0x_suspect_theft_initiator',
        '0x_mule_account_alpha',
        '0x_peeling_layer_01',
        '0x_dep_coindcx_user_4492',
        'CoinDCX Main Inflow Vault',
      ],
    },
    metrics: {
      total_hops_traversed: 4,
      total_volume_traced_crypto: 381.75,
      high_risk_flags_tripped: [
        'Sanctioned Mixer Interaction (OFAC SDN List / Tornado Cash)',
        'Asymmetric Peeling Chain Detected (> 80/20 Layering)',
        'Rapid Exchange Consolidation Sweep (> 95% Inflow Consolidation)',
      ],
      nearest_identified_vasp: {
        entity_name: 'CoinDCX (Neblio Technologies Pvt. Ltd.)',
        jurisdiction: 'India (FIU-IND Registered)',
        compliance_email: 'compliance@coindcx.com',
      },
    },
  },
};
